repos:
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: v3.21.3
      hooks:
        - id: commitizen
          stages: [commit-msg]

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace

  -   repo: https://github.com/hhatto/autopep8
      rev: v2.1.0
      hooks:
      -   id: autopep8

  -   repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
      -   id: black
          args: [--line-length=79]

  -   repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
      -   id: flake8
          args: ['--ignore=E129,E501']
