---
version: '3.4'

x-common:
  &common
  image: apache/airflow:2.8.3
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - .env
  volumes:
    - .airflow/dags:/opt/airflow/dags
    - .airflow/logs:/opt/airflow/logs
    - .airflow/plugins:/opt/airflow/plugins
    - .airflow/scripts:/opt/airflow/scripts
    - .airflow/sql:/opt/airflow/sql
    - .airflow/files:/opt/airflow/files
    - .airflow/events-api:/opt/airflow/events-api
    - /var/run/docker.sock:/var/run/docker.sock
    - .postgres/transfer:/var/transfer:rw

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - .postgres/database:/var/lib/postgresql/data
      - .postgres/transfer:/var/transfer:rw
      - ./docker_postgres_init_dl.sql:/docker-entrypoint-initdb.d/docker_postgres_init_dl.sql
      - ./docker_postgres_init_dw.sql:/docker-entrypoint-initdb.d/docker_postgres_init_dw.sql
    ports:
      - "5455:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env

  scheduler:
    <<: *common
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"

  webserver:
    <<: *common
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version

  app:
    restart: always
    build:
      context: ./
    ports:
      - 80:5000
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    env_file:
      - .env

